import numpy as np

## Previous version, fill_dict.py
#Fill values dictionary
Fill_dict = {"Year": np.nan, "Day": np.nan, "Hour": np.nan, "Bartels": 9999, "ID-IMF": 99, "ID-SW": 99, "nop-IMF": 999, "nop-plasma": 999, "FMA": 999.9, "Mag-AFV": 999.9, "Lat-AFV": 999.9, "Long-AFV": 999.9, "Bx": 999.9, "By GSE": 999.9, "Bz GSE": 999.9, "By GSM": 999.9, "Bz GSM": 999.9,
"sigma absB": 999.9, "sigma B": 999.9, "sigma Bx": 999.9, "sigma By": 999.9, "sigma Bz": 999.9, "ProTemp": 9999999., "ProDens": 999.9, "FlowSpeed": 9999, "FlowLong": 999.9, "FlowLat": 999.9, "Na/Np": 9.999, "FlowPres": 99.99, "sigma T": 9999999., "sigma N": 999.9, "sigma V": 9999.,
"sigma pV": 999.9, "sigma tV": 999.9, "sigma Na/Np": 9.999, "Efield": 999.99, "Pbeta": 999.99, "Alfven": 999.9, "Kp": 99, "R": 999, "DST": 99999, "AE": 9999, "Pflux-1": 999999.99, "Pflux-2": 99999.99, "Pflux-4": 99999.99, "Pflux-10": 99999.99, "Pflux-30": 99999.99, "Pflux-60": 99999.99,
"ap": 999, "f10.7": 999.9, "PC(N)": 999.9, "AL": 99999, "AU": 99999, "Mgsonic": 99.9}


## Updated version, column_dict.py
#Column names as keys, Description and bad data placeholders as values
Column_dict = {"Year": ["Between 1964-2021", np.nan], "Day": ["Jan 1 = Day 1", np.nan], "Hour": ["Value from 0-23 for each hour in day", np.nan], "Bartels": ["Average number of solar rotations since 1932", 9999], "ID-IMF": ["Identifier for spacecraft gathering IMF data", 99], "ID-SW": ["Identifier for spacecraft gathering SW-Plasma data", 99], "nop-IMF": ["Number of fine time scale points in IMF avg", 999], "nop-plasma": ["Number of fine time scale points in SW-Plasma avg", 999], "FMA": ["Average of magnetic field magnitudes, (nT)", 999.9], "Mag-AFV": ["Magnitude of average magnetic field vector, (nT)", 999.9], "Lat-AFV": ["Lateral angle of average field vector (GSE coords, degrees)", 999.9], "Long-AFV": ["Longitudinal angle of average field vector (GSE coords, degrees)", 999.9], "Bx GSE": ["X-component of magnetic field (GSE coords, nT)", 999.9], "By GSE": ["Y-component of magnetic field (GSE coords, nT)", 999.9], "Bz GSE": ["Z-component of magnetic field (GSE coords, nT)", 999.9], "By GSM": ["Y-component of magnetic field (GSM coords, nT)", 999.9], "Bz GSM": ["Z-component of magnetic field (GSM coords, nT)", 999.9],
"sigma absB": ["RMS Standard deviation in avg magnitude (nT)", 999.9], "sigma B": ["RMS Standard deviation in field vector (nT)", 999.9], "sigma Bx": ["RMS Standard deviation in GSE X component avg (nT)", 999.9], "sigma By": ["RMS Standard deviation in GSE Y component avg (nT)", 999.9], "sigma Bz": ["RMS Standard deviation in GSE Z component avg (nT)", 999.9], "ProTemp": ["SW Proton Temperature (K)", 9999999], "ProDens": ["SW Proton density (per cubic cm)", 999.9], "FlowSpeed": ["SW Plasma flow speed (km/s)", 9999], "FlowLong": ["SW Plasma flow longitudinal angle (phi-V, degrees)", 999.9], "FlowLat": ["SW Plasma flow lateral angle (theta-V, degrees)", 999.9], "Na/Np": ["Ratio of alpha particles to protons in SW", 9.999], "FlowPres": ["SW Plasma flow pressure (nPa)", 99.99], "sigma T": ["Standard Deviation in proton temperature (K)", 9999999], "sigma N": ["Standard Deviation in proton density (per cubic cm)", 999.9], "sigma V": ["Standard Deviation in flow speed (km/s)", 9999],
"sigma pV": ["Standard Deviation in flow longitudinal angle (degrees)", 999.9], "sigma tV": ["Standard Deviation in flow lateral angle (degrees)", 999.9], "sigma Na/Np": ["Standard Deviation in alpha/proton ratio", 9.999], "Efield": ["Electric field derived from flow speedand magnetic field (mV/m)", 999.99], "Pbeta": ["Ratio between plasma pressure and magnetic pressure", 999.99], "Alfven": ["Ratio between the speed of magnetic field waves (Alfven waves) and the speed of sound in the surrounding medium", 999.9], "Kp": ["A measure of the amount of disturbance to Earth's magnetic field by solar wind", 99], "R": ["Daily sunspot number", 999], "DST": ["An indicator of the magnetic intensity of the equatorial 'ring current' around Earth (nT)", 99999], "AE": ["A measure of auroral zone magentic activity", 9999], "Pflux-1": ["Particle flux for solar protons with energy > 1MeV (per square cm)", 999999.99], "Pflux-2": ["Particle flux for solar protons with energy > 2MeV (per square cm)", 99999.99], "Pflux-4": ["Particle flux for solar protons with energy > 4MeV (per square cm)", 99999.99], "Pflux-10": ["Particle flux for solar protons with energy > 10MeV (per square cm)", 99999.99], "Pflux-30": ["Particle flux for solar protons with energy > 30MeV (per square cm)", 99999.99], "Pflux-60": ["Particle flux for solar protons with energy > 60MeV (per square cm)", 99999.99], "M'SPH Flux Flag": ["Indicates how much the magnetosphere contributes to the proton flux", np.nan],
"ap": ["Ap is a linear index for geomagnetic disturbance that correlates with the Kp index (nT)", 999], "f10.7": ["Measure of solar radiation flux specifically at a wavelength of 10.7cm (10**-22 W/m)", 999.9], "PC(N)": "Polar Cap index measures the effect of solar winds in geomagnetic activity around the poles", 999.9], "AL": ["Amplitude Lower is the lower boundary of geomagnetic activity recorded by magnetometers (nT)", 99999], "AU": ["Amplitude Upper is the upper boundary of geomagnetic activity recorded by magnetometers (nT)", 99999], "MGS mach": ["Magnetosonic mach number is the ratio between solar wind speed and magnetosonic speed", 99.9], "lyman-alpha": ["Daily average intensity of solar lyman-alpha radiation (W/m^2)", 0.999999], "ProQI": ["I do not know what a Proton Quasi-Invariant is", 9.9999]}